name: login_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  flutter:
    sdk: flutter
  icons_plus: ^5.0.0
  intl: ^0.20.2
  dotted_border: ^3.0.1
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  #qr_code_scanner: ^1.0.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/loguitppp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Icons/
  fonts:
    - family: MiFuente
      fonts:
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
        # - asset: assets/fonts/Jersey_15/Jersey15-Regular.ttf